# Generated by Django 6.0.2 on 2026-04-10 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0003_alter_product_active_alter_product_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="slug",
            field=models.SlugField(default="kdkdkdkd"),
        ),
    ]
