# Generated by Django 6.0.2 on 2026-04-10 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0004_product_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(default="kdkdkdkd", unique=True),
        ),
    ]
