# Generated by Django 6.0.3 on 2026-06-03 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_category_parent_productvariants_is_pack_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='colors_available',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='product',
            name='memories_available',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='product',
            name='models_available',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
