# Generated by Django 6.0.3 on 2026-06-12 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='models_available',
        ),
        migrations.RemoveField(
            model_name='productvariants',
            name='model',
        ),
    ]
