# Generated by Django 6.0.3 on 2026-07-04 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_story'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariants',
            name='memory',
        ),
        migrations.AddField(
            model_name='product',
            name='intercom_monitor_size',
            field=models.CharField(blank=True, choices=[('4.3', '4.3 اینچ'), ('7', '7 اینچ')], max_length=10, null=True, verbose_name='اندازه صفحه (آیفون تصویری)'),
        ),
        migrations.AddField(
            model_name='productvariants',
            name='has_recording_memory',
            field=models.BooleanField(default=False, verbose_name='قابلیت ذخیره تصویر'),
        ),
        migrations.AddField(
            model_name='productvariants',
            name='unit_count',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1 واحدی'), (2, '2 واحدی'), (3, '3 واحدی'), (4, '4 واحدی')], null=True, verbose_name='تعداد واحد'),
        ),
    ]
