# Generated by Django 6.0.3 on 2026-07-06 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_productvariants_memory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='نام رنگ')),
            ],
            options={
                'verbose_name': 'رنگ',
                'verbose_name_plural': 'رنگ\u200cها',
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='colors_available',
        ),
        migrations.RemoveField(
            model_name='product',
            name='memories_available',
        ),
        migrations.AlterField(
            model_name='productvariants',
            name='is_pack',
            field=models.BooleanField(default=False, verbose_name='آیا پک است؟'),
        ),
        migrations.AlterField(
            model_name='productvariants',
            name='unit_count',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1 واحدی'), (2, '2 واحدی'), (3, '3 واحدی'), (4, '4 واحدی')], null=True, verbose_name='تعداد واحد (برای پک)'),
        ),
        migrations.AlterField(
            model_name='productvariants',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variants', to='products.color', verbose_name='رنگ'),
        ),
    ]
