# Generated by Django 6.0.3 on 2026-07-08 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_color_remove_product_colors_available_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='color',
            options={'verbose_name': 'color', 'verbose_name_plural': 'colors'},
        ),
        migrations.AlterField(
            model_name='color',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='color name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='intercom_monitor_size',
            field=models.CharField(blank=True, choices=[('4.3', '4.3 اینچ'), ('7', '7 اینچ')], max_length=10, null=True, verbose_name='size'),
        ),
        migrations.AlterField(
            model_name='productvariants',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variants', to='products.color', verbose_name='color'),
        ),
    ]
